---
title: "chpater 4"
author: "Adam Gruer"
date: "30/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```


POsterior will be a distribution of distributions?
```{r}
data("Howell1")
d <- Howell1
precis(d)

d2 <- d[d$age >= 18, ]
dens(d2$height)
range(d2$height)

curve( dnorm(x, 178, 20), from = 100, to = 250)
curve(dunif(x , 0, 50), from = -10, to = 60)
```
# Prior predictive sumulaiton
h_i ~ Normal(mu, sigma)  - likelihood
mu ~ Normal(178, 20)    mu prior
sigma ~  Normal(0, 50)

```{r}
sample_mu <- rnorm(1e4, 178, 20)
sample_sigma <- runif(1e4, 0, 50)
prior_h <- rnorm(1e4, sample_mu, sample_sigma)
dens(prior_h, norm.comp = TRUE)
```

```{r}
mu.list <- seq(from = 150, to = 160, length.out = 100)
sigma.list <- seq(from = 7, to = 9,length.out = 100)
post <- expand.grid(mu=mu.list, sigma = sigma.list)
post$LL <- sapply(1:nrow(post), function(i) sum(
  dnorm(d2$height, post$mu[i], post$sigma[i], log=TRUE)))
post$prod <- post$LL + dnorm( post$mu, 178, 20, TRUE) + 
  dunif(post$sigma, 0, 50, TRUE)
post$prob <- exp(post$prod - max(post$prod))
contour_xyz(post$mu, post$sigma, post$prob)
image_xyz(post$mu, post$sigma, post$prob)

#sample from posterior probability distributiun
sample.rows <- sample(1:nrow(post), size = 1e4, replace = TRUE, prob = post$prob)
sample.mu <- post$mu[ sample.rows]
sample.sigma <- post$sigma[ sample.rows]

plot(sample.mu, sample.sigma, cex = 0.5, pch = 16, col = col.alpha(rangi2, 0.1))

dens(sample.mu)
dens(sample.sigma)

PI(sample.mu)
PI(sample.sigma)




```

```{r}
d3 <- sample(d2$height, size = 20)
mu.list <- seq(from = 150, to = 170, length.out = 200)
sigma.list <- seq(from = 4, to = 20,length.out = 200)
post2 <- expand.grid(mu=mu.list, sigma = sigma.list)
post2$LL <- sapply(1:nrow(post2), function(i) sum(
  dnorm(d3, post2$mu[i], post2$sigma[i], log=TRUE)))
post2$prod <- post2$LL + dnorm( post2$mu, 178, 20, TRUE) + 
  dunif(post2$sigma, 0, 50, TRUE)
post2$prob <- exp(post2$prod - max(post2$prod))
contour_xyz(post2$mu, post2$sigma, post2$prob)
image_xyz(post2$mu, post2$sigma, post2$prob)

#sample from posterior probability distributiun
sample2.rows <- sample(1:nrow(post2), size = 1e4, replace = TRUE, prob = post2$prob)
sample2.mu <- post2$mu[ sample2.rows]
sample2.sigma <- post2$sigma[ sample2.rows]

plot(sample2.mu, sample2.sigma, cex = 0.5, pch = 16, col = col.alpha(rangi2, 0.1))

dens(sample2.mu)
dens(sample2.sigma)

PI(sample2.mu)
PI(sample2.sigma)




```


# posterior distribution with quap

```{r}
flist <- alist(
  height ~ dnorm(mu, sigma),
  mu ~ dnorm(178, 20),
  sigma <- dunif(0, 50)
)

m4.1 <- quap(flist, data = d2)

precis(m4.1)

vcov(m4.1)
diag(vcov(m4.1))
cov2cor(vcov(m4.1))

post <- extract.samples(m4.1, n=1e4)
head(post)

precis(post)
plot(post)
```

## Linear prediction

```{r}
library(ggplot2)
ggplot(data = d2) +
  geom_point(aes(x = weight, y = height))
```

Prior predictive simulation

```{r}

set.seed(2971)
N <- 100
a <- rnorm(N, 178, 20)
b <- rnorm(N, 0, 10)
```

#4.39
```{r}
lines <- purrr::map2(a, b, function(a, b) {
  geom_function(fun = function(x){
    a + b * (x - mean(d2$weight))
  }, alpha = 0.2,
  )
})

ggplot(data =  d2, aes(x = weight)) +
  lines +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 272) +
  coord_cartesian(ylim = c(-100, 400)) +
  labs(title = "b ~ dnorm(0,10)")

```

```{r}
b <- rlnorm(1e4, 0, 1)
dens(b, xlim= c(0,5), adj = 0.1)
```

```{r}
set.seed(2971)
N <- 100
a <- rnorm(N, 178, 20)
b <- rlnorm(N, 0, 1)

lines <- purrr::map2(a, b, function(a, b) {
  geom_function(fun = function(x){
    a + b * (x - mean(d2$weight))
  }, alpha = 0.2,
  )
})

ggplot(data =  d2, aes(x = weight)) +
  lines +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 272) +
  coord_cartesian(ylim = c(-100, 400)) +
  labs(title = "log(b) ~ dnorm(0,1)")
```

```{r}
#average weight xbar
xbar <- mean(d2$weight)

#fit omdel
m4.3 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * (weight - xbar),
    a ~ dnorm(178, 20),
    b ~ dlnorm(0, 1),
    sigma ~ dunif(0, 50)
  ),
  data = d2
)

precis(m4.3)
round( vcov(m4.3), 3)


```
```{r}
post <- extract.samples(m4.3)
a_map <- mean(post$a)
b_map <- mean(post$b)

ggplot() +
  geom_point(data = d2, aes(y = height, x = weight), colour = rangi2) +
  geom_function(fun = function(x) {a_map + b_map*(x - xbar)})
  
```
```{r}
post <- extract.samples(m4.3)
post[1:5, ]
```

```{r}
N <- 10


dN <- d2[1:N, ]
mN <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * (weight - mean(weight)),
    a ~ dnorm(178, 20),
    b ~ dlnorm(0, 1),
    sigma ~ dunif(0, 50)
  ),
  data = dN
)

post <- extract.samples(mN, n = 20)

lines <- purrr::map2(post$a, post$b, function(a, b) {
  geom_function(fun = function(x){
    a + b * (x - mean(dN$weight))
  }, alpha = 0.2,
  )
})

ggplot(data =  dN, aes(x = weight, y = height )) +
  geom_point(colour = rangi2) +
  lines +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 272) +
  coord_cartesian(ylim = range(d2$height), xlim = range(d2$weight)) +
  labs(title = paste("N = ", N)) 
```
```{r}
N <- 100


dN <- d2[1:N, ]
mN <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b * (weight - mean(weight)),
    a ~ dnorm(178, 20),
    b ~ dlnorm(0, 1),
    sigma ~ dunif(0, 50)
  ),
  data = dN
)

post <- extract.samples(mN, n = 20)

lines <- purrr::map2(post$a, post$b, function(a, b) {
  geom_function(fun = function(x){
    a + b * (x - mean(dN$weight))
  }, alpha = 0.2,
  )
})

ggplot(data =  dN, aes(x = weight, y = height )) +
  geom_point(colour = rangi2) +
  lines +
  geom_hline(yintercept = 0, linetype = "dashed") +
  geom_hline(yintercept = 272) +
  coord_cartesian(ylim = range(d2$height), xlim = range(d2$weight)) +
  labs(title = paste("N = ", N)) 

```

```{r}
post <- extract.samples(m4.3)
mu_at_50 <- post$a + post$b * (50 - xbar)
dens(mu_at_50, col = rangi2, lwd = 2, xlab="mu|weight=50")
```
```{r}
PI(mu_at_50, prob = 0.89)
```
```{r}
mu <- link(m4.3)
str(mu)
```

# 4.55 

```{r}
weight.seq <- seq(from=25, to=70, by = 1)

mu <- link(m4.3, data = data.frame(weight=weight.seq))
str(mu)

#plot(height ~ weight, d2, type = "n")
library(dplyr)
library(tidyr)

top_100 <- as.data.frame(t(mu[1:1000, ])) %>% 
  dplyr::mutate(weight = weight.seq, .before = V1) %>% 
  tidyr::pivot_longer(cols = V1:V100, names_to = "sample_no", values_to = "height" )

ggplot() +
  geom_point(data = top_100, aes(x = weight, y = height), colour = rangi2, alpha = 0.2) +
  coord_cartesian(ylim = range(d2$height), xlim = range(d2$weight))
```
# 4.56

```{r}
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI, prob=0.89)
```

#4.57 

```{r}
ggplot() +
  geom_point(data = d2,
             aes(x = weight , y = height),
             colour = col.alpha(rangi2, 0.5),
             shape = 1
             ) +
  geom_line(data = data.frame(weight = weight.seq, height = mu.mean),
            aes(x = weight, y = height)) +
   coord_cartesian(ylim = range(d2$height), xlim = range(d2$weight)) +
  geom_ribbon(data = data.frame(weight = weight.seq,
                                ymin = t(mu.PI)[,1],
                                ymax = t(mu.PI)[,2]),
              aes(x = weight, ymax = ymax, ymin = ymin),
              alpha = 0.3, colour = "grey80")

col.alpha(rangi2, 0.5)
```

#4.59

```{r}
sim.height <- sim(m4.3, data = list(weight = weight.seq), n = 1e4)

height.PI <- apply(sim.height, 2, PI , prob= 0.89)
height.PI.df <- height.PI %>%
  t() %>%
  as.data.frame() %>% 
  mutate(weight = weight.seq, .before = 1)




ggplot() +
    geom_point(data = d2,
             aes(x = weight , y = height),
             colour = col.alpha(rangi2, 0.5),
             shape = 1
             ) +
  geom_line(data = data.frame(weight = weight.seq, height = mu.mean),
            aes(x = weight, y = height)) +
   coord_cartesian(ylim = range(d2$height), xlim = range(d2$weight)) +
    geom_ribbon(data = height.PI.df,
              aes(x = weight, ymax = `5%`, ymin = `94%`),
              alpha = 0.3, colour = "grey80") + 
  geom_ribbon(data = data.frame(weight = weight.seq,
                                ymin = t(mu.PI)[,1],
                                ymax = t(mu.PI)[,2]),
              aes(x = weight, ymax = ymax, ymin = ymin),
              alpha = 0.3, colour = "grey70") 

  
  
```


# Polynomial regression

```{r}
d <-  Howell1
qplot(x = weight, y = height, data = d)

```

# 4.65
```{r}
d$weight_s <- (d$weight - mean(d$weight)) /sd(d$weight)
d$weight_s2 <- d$weight_s^2

m4.5 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b1*weight_s + b2*weight_s2,
    a ~ dnorm(178, 20),
    b1 ~ dlnorm(0, 1),
    b2 ~ dnorm(0, 1),
    sigma ~ dunif(0, 50)
  ), 
  data = d
)
```

# 4.66

```{r}
precis(m4.5)
```

# 4.67

```{r}


PI.df <- function(m, x){
  t(m) %>% 
    as.data.frame() %>% 
    dplyr::mutate(x = x, .before = 1) %>% 
    janitor::clean_names()
    
}
range(d$weight_s)
weight.seq <- seq(from = -2.2, to = 2, length.out = 30)
pred_data <- data.frame(weight_s = weight.seq, weight_s2 = weight.seq^2)
mu <- link(m4.5, data = pred_data)
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI, prob = 0.89)
mu.PI.df <- PI.df(mu.PI, weight.seq)
sim.height <- sim(m4.5, data = pred_data)
height.PI <- apply(sim.height, 2, PI, prob = 0.89)
height.PI.df <- PI.df(height.PI, weight.seq)


ggplot() +
    geom_ribbon(data = height.PI.df,
              aes(x = x,
                  ymin = x5_percent,
                  ymax = x94_percent),
             alpha = 0.2,
              colour = "grey90") +
      geom_ribbon(data = mu.PI.df,
              aes(x = x,
                  ymin = x5_percent,
                  ymax = x94_percent),
             alpha = 0.2,
              colour = "grey80") +
  geom_point(data = d, 
             aes(x = weight_s, y = height) ,
             shape = 1,
             colour = rangi2,
             alpha = 0.5) +
  geom_line(data = data.frame(weight_s = weight.seq, mu.mean = mu.mean ),
            aes(x = weight_s, y = mu.mean)) 


```

# 4.69

```{r}
d$weight_s3 <- d$weight_s^3

m4.6 <- quap(
  alist(
    height ~ dnorm(mu, sigma),
    mu <- a + b1*weight_s + b2*weight_s2 + b3*weight_s3,
    a ~ dnorm(178, 20),
    b1 ~ dlnorm(0, 1),
    b2 ~ dnorm(0, 10),
    b3 ~ dnorm(0, 10),
    sigma ~ dunif(0, 50)
  ), 
  data = d
)

PI.df <- function(m, x){
  t(m) %>% 
    as.data.frame() %>% 
    dplyr::mutate(x = x, .before = 1) %>% 
    janitor::clean_names()
    
}
range(d$weight_s)
weight.seq <- seq(from = -2.2, to = 2, length.out = 30)
pred_data <- data.frame(weight_s = weight.seq, weight_s2 = weight.seq^2, weight_s3 = weight.seq^3)
mu <- link(m4.6, data = pred_data)
mu.mean <- apply(mu, 2, mean)
mu.PI <- apply(mu, 2, PI, prob = 0.89)
mu.PI.df <- PI.df(mu.PI, weight.seq)
sim.height <- sim(m4.6, data = pred_data)
height.PI <- apply(sim.height, 2, PI, prob = 0.89)
height.PI.df <- PI.df(height.PI, weight.seq)


p <- ggplot() +
    geom_ribbon(data = height.PI.df,
              aes(x = x,
                  ymin = x5_percent,
                  ymax = x94_percent),
             alpha = 0.2,
              colour = "grey90") +
      geom_ribbon(data = mu.PI.df,
              aes(x = x,
                  ymin = x5_percent,
                  ymax = x94_percent),
             alpha = 0.2,
              colour = "grey80") +
  geom_point(data = d, 
             aes(x = weight_s, y = height) ,
             shape = 1,
             colour = rangi2,
             alpha = 0.5) +
  geom_line(data = data.frame(weight_s = weight.seq, mu.mean = mu.mean ),
            aes(x = weight_s, y = mu.mean)) 
p

at <- c(-2,-1,0,1,2)

p +
    scale_x_continuous("standardized weight converted back",
                     breaks = at,
                     labels = round(at * sd(d$weight) + mean(d$weight), 1))
```

#Splines

## 4.72

```{r}
library(rethinking)
data("cherry_blossoms")
d <- cherry_blossoms
precis(d)
?cherry_blossoms
View(d)
qplot(x = year, y = temp, data = d)


```

## 4.73

```{r}
d2 <- d[complete.cases(d$temp), ]
num_knots <- 15
knot_list <- quantile(d2$year, probs = seq(0, 1, length.out = num_knots))
knot_list

```
## 4.74

```{r}
library(splines)

B <- bs(d2$year,
        knots = knot_list[-c(1,num_knots)],
        degree = 3, intercept = TRUE)

B
```

## 4.75

```{r}
plot.new()
plot(NULL, xlim=range(d2$year), ylim=c(0,1), xlab="year", ylab="basis value")
for( i in 1:ncol(B)) lines(d2$year, B[,i])

B.df <- as.data.frame(B)
B.df$year <- d2$year
B.df <- B.df %>% 
  pivot_longer(cols = -year, names_to = "basis", values_to = "basis_value") 
ggplot(data = B.df, aes(x = year, y = basis_value, group = basis, colour = basis)) +
  geom_line(show.legend = FALSE)
  
```


## 4.76

```{r}
mean(d2$temp)

m4.7 <-  quap(
  alist(
    T ~ dnorm(mu, sigma) ,
    mu <- a + B %*% w,
    a ~ dnorm(6, 10),
    w ~ dnorm(0, 1),
    sigma ~ dexp(1)
),
data = list(T = d2$temp, B = B),
start = list(w = rep(0, ncol(B))))

precis(m4.7, depth = 2)
```

## 4.77

```{r}
post <- extract.samples(m4.7)
w <- apply(post$w, 2, mean)
plot(NULL, xlim=range(d2$year), ylim=c(-2,2),
     xlab="year", ylab="basis * weight")
for ( i in 1:ncol(B)) lines(d2$year, w[i] * B[,i])


weight.basis.df <- sapply(1:ncol(B), function(i) w[i] * B[, i]) %>% 
  as.data.frame()
weight.basis.df$year <- d2$year

weight_basis.df <- pivot_longer(weight.basis.df,
                                -year,
                                values_to = "basis_x_weight",
                                names_to = "basis")
ggplot(data = weight_basis.df,
       aes(x = year, y = basis_x_weight, group = basis)) +
  geom_line()



```


```{r}
mu <- link(m4.7)
mu_PI <- apply(mu, 2,  PI, prob=0.97)

mu_PI.df <- PI.df(mu_PI, d2$year)

ggplot() +
  geom_ribbon(data = mu_PI.df, 
              aes(x = x, ymin = x2_percent, ymax = x98_percent),
              colour = "grey80",
              alpha = 0.3) +
  geom_point(data = d2, aes(x = year, y = temp),
             colour = rangi2,
             alpha = 0.3, 
             shape = 1)

```

